---
- name: "Create directory ~/booking if it does not exist"
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/booking
    state: directory
    mode: "0755"

- name: "Create a docker network for booking"
  community.docker.docker_network:
    name: booking_network

- name: "Copy docker-compose.yml"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/booking/docker-compose.yml
    mode: preserve

- name: "Copy nginx.conf"
  ansible.builtin.copy:
    src: nginx.conf
    dest: /home/{{ ansible_user }}/booking/
    mode: "0644"

- name: "Copy .env"
  ansible.builtin.copy:
    src: .env
    dest: /home/{{ ansible_user }}/booking/
    mode: "0644"

- name: "Create and start booking"
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/booking
  register: output

- name: "Show results"
  ansible.builtin.debug:
    var: output
