upstream app {
    server 'app:3000';
}

server {
    listen 80;

    server_name _;
    
    access_log /var/log/nginx.access.log;
    error_log /var/log/nginx.error.log info;

    location / {
        proxy_pass http://app;
        proxy_set_header Host $host;
    }
}
